### PR TITLE
Fixed some typos and slightly enhanced grammar

### PR DESCRIPTION
**Pull request by jonathanarbely**

### CODE REVIEW

**Comment by hoxxep** [comment]
Cheers for the docs tidy up! 👍

**Comment by jonathanarbely** [comment]
Thanks for the approval! Will this be merged? If yes, I'd be happy to cover more mistakes and further enhance grammar.

**Comment by hoxxep** [comment]
I reckon it will be when @fians is next online, I sadly don't have merge privileges but I don't see any reason why it wouldn't be 👍

**Comment by jonathanarbely** [comment]
Hey @hoxxep, can you pull this in? Cheers.

**Comment by fians** [comment]
Thanks @jonathanarbely !

**Pull request merged**
