### PR TITLE
Used span instead of i element for input/submit button. Also removed …

### PR DESCRIPTION
**Pull request by ralphbolliger**
…inline styles for wrapper and element because it caused invisibility on inputs/submits.

### CODE REVIEW

**Comment by fians** [comment]
Let me check it first. Thanks @ralphbolliger!

**Comment by fians** [comment]
@ralphbolliger Hi, can you create a fiddle to show me the invisibility issue you mention it before? Thanks!

**Comment by ralphbolliger** [comment]
@fians, fo course. Here we go: https://jsfiddle.net/ralphbolliger/3dtj6b1h/

**Comment by fians** [comment]
Merge to 0.8.0-dev. Thanks @ralphbolliger!

**Pull request closed without merging**
